---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: click-counter-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: cizi/click-counter-backend
        name: backend
        ports:
        - containerPort: 9001
          name: http
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: click-counter-backend-svc
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9001
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: click-counter-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - env:
        - name: BACKEND_SERVICE
          value: "http://click-counter-backend-svc/api/counter"
        image: cizi/click-counter-frontend
        name: frontend
        ports:
        - containerPort: 9000
          name: http
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: click-counter-frontend-svc
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9000
---